### PR TITLE
Updates for Scala 2.13

### PR DESCRIPTION
**Pull request by travisbrown**
Includes everything from https://github.com/sangria-graphql/sangria-marshalling-api/pull/5, including @ingemaradahl's commits from https://github.com/sangria-graphql/sangria-marshalling-api/pull/4.

No errors from:
```
sbt ++2.11.12 mimaReportBinaryIssues
sbt ++2.12.10 mimaReportBinaryIssues
```
…so we can publish as 1.0.4.

### CODE REVIEW

**Comment by travisbrown** [comment]
Repushed last commit to trigger Travis CI.

**Comment by ingemaradahl** [comment]
Thank you for doing this! Would you mind squashing my fixup commit?

**Comment by travisbrown** [comment]
@ingemaradahl Sure, will do it this morning!

**Comment by travisbrown** [comment]
Okay, fixup is squashed, changelog is updated, and I've added sbt-release.

**Comment by travisbrown** [comment]
Oh, sorry, squashed the fixup in the wrong place. Now it's right.

**Review by yanns — APPROVED** [review]
Let's try to release 🚀

**Comment by travisbrown** [comment]
@yanns :+1: I'll kick it off now.

**Comment by travisbrown** [comment]
@yanns It worked—the staging repo looks fine! Maybe I should go ahead and close and release this one, and you can try https://github.com/sangria-graphql-org/sangria-streaming-api/pull/1?

**Comment by yanns** [comment]
@travisbrown have you used `sbt release`. Does it automatically publish to maven, or do you have to go a manual step?

**Comment by travisbrown** [comment]
@yanns sbt-release will publish to a staging repo, and then you have to log into https://oss.sonatype.org/ and click "close" and then "release".

sbt-sonatype can automate that for you, but I personally find it useful to be forced to check the artifacts, and given that these libraries aren't likely to change terribly often, I think sbt-release without sbt-sonatype will be fine.

**Comment by yanns** [comment]
OK thx for the info.
I'm used to a complete automated process here (that's why I proposed to use `sbt-sonatype`).
I'm ok with the manual step in the first place.

**Comment by travisbrown** [comment]
@yanns For the record, for this 1.0.4 release here's what I did:

1. Merged this PR.
2. Pulled this master branch locally.
3. Made sure my `.sbt/.credentials` config was correct.
4. Ran `sbt release`.
5. Chose the defaults for version and next (snapshot) version when prompted in the console.
6. Entered my passphrase when prompted by the sbt-pgp pop-up.
7. Logged into https://oss.sonatype.org/.
8. Clicked "Staging Repositories" under "Build Promotion".
9. Selected the `org.sangria-graphql` repo and clicked "Close".
10. Waited until it was available again and clicked "Release".
11. Pushed the release commit and tag to this repo.

**Comment by travisbrown** [comment]
(For step 11. I pushed the commit and tag manually, with `git push tmp master` and `git push tmp --tags`, since I named this remote `tmp` and wasn't sure whether the automated push would try to send them to `origin`. Depending on what your local remote setup looks like that may not be necessary.)

**Comment by travisbrown** [comment]
Also I'm happy to add sbt-sonatype—I only have a weak preference for not using it.

**Comment by travisbrown** [comment]
To confirm: yes, sbt-release will try to push to `origin`, so you either have to change your `origin` to point here or do that last step manually.

**Pull request merged**
